/* eslint-disable import/no-unresolved */
import Head from 'next/head'

import ListView from '@/components/ListView'

export default function Home() {
  return (
    <>
      <Head>
        <title>Todos avec next.js et rxjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex flex-col items-center justify-center">
        <h1 className=" text-2xl">Mes listes</h1>
        <ListView />
      </main>
    </>
  )
}
